#!/usr/bin/env bash
set -euo pipefail

sudo chmod +x /home/pi-collector/edge_data_processor/video_gather/record_video.py
sudo systemctl daemon-reload
sudo systemctl enable record-video.service
sudo reboot
